### PR TITLE
Encrypted session cookies

### PR DESCRIPTION
**Pull request by mjc-gh**
PR for issue #1300.

### CODE REVIEW

**Comment by mikeycgto** [comment]
Any hope of this eventually getting merged? Should we add a way of opting-in to this feature to start off initially?

/cc @zzak

**Comment by mikeycgto** [comment]
@namusyaka I see this was tagged for 2.1.0. Let me know if there's any more work to do on this PR to get it ready for merging. Thanks!

**Comment by namusyaka** [comment]
@mikeycgto Yeah we're going to get this in v2.1.0, thank you for your contribution!

**Comment by mikeycgto** [comment]
Excellent! Just ping me here if there's anything that needs to be changed or updated. Thanks again!

**Comment by bermannoah** [comment]
Hi there, looks like it's been a while -- any word on this getting merged / released?

**Comment by bsene** [comment]
@mjc-gh  there are some conflicts , resolve them may make your work to be merged

**Pull request merged**
