### PR TITLE
Adding falcon integration

### PR DESCRIPTION
**Pull request by horaciob**
#1639 
Dont know if I have to do something else, I saw puma's integration, it works on local.

Puma will be default if exist.

I've tried with jruby but looks like falcon has some issues with jruby

### CODE REVIEW

**Comment by namusyaka** [comment]
@jkowens Could you take a look?

**Comment by jkowens** [comment]
Looks good to me, except that Falcon server doesn't shutdown gracefully like our other Rack servers when hitting ctrl + c:

```
/lib/sinatra/base.rb:1478:in `quit!': undefined method `stop' for #<Falcon::Server:0x00007f9729945620> (NoMethodError)
```

@horaciob is there a way to make that work?

**Comment by horaciob** [comment]
They have some issues related to gracefull ([shutdown](https://github.com/socketry/falcon/issues/114) and [restart](https://github.com/socketry/falcon/issues/71)), let me see if are related with this or i can do something to avoid this.

**Comment by ioquatix** [comment]
This is the problem code:

https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1481-L1489

It assumes the server responds to `#stop`. So, for this to work, either we need to realise not all servers respond to `stop!` or `stop` and write a wrapper which invokes the correct method, or we need to add `#stop` to `Falcon::Server` some how.

**Comment by jkowens** [comment]
Replaced by #1794

**Pull request closed without merging**
