### PR TITLE
Drop support for Stylus

### PR DESCRIPTION
**Pull request by epergo**
Contributes to https://github.com/sinatra/sinatra/issues/1690

> stylus hasn't been maintained for a long time. Support for stylus will be dropped in the next major version upgrade.

### CODE REVIEW

**Comment by zzak** [comment]
@epergo I'm thinking we should start a branch called `unstable` or something that we can start making 3.x PRs against. 🤔

**Comment by epergo** [comment]
> @epergo I'm thinking we should start a branch called `unstable` or something that we can start making 3.x PRs against. 🤔

It makes sense, if not we are going to have a lot PRs piled up until we decide to start merging them. Another alternative could be having branches per stable releases and treat `master` like edge (like I think Rails does), but I guess that is more cumbersome for maintainers so whatever works for you 😄

**Comment by zzak** [comment]
@epergo The reason I want to avoid merging many unreleased changes to `main` is that releases in the past have been slow and I know some people are just using `github "sinatra/sinatra"` in their Gemfiles.

**Comment by epergo** [comment]
Sounds good to me! As soon as we have the `unstable` branch I'll update the PR

**Review by namusyaka — APPROVED** [review]

**Comment by epergo** [comment]
@zzak I changed the target branch to `unstable` do you think we can merge this?

**Pull request merged**
