### PR TITLE
Use Mustermann for patterns

### PR DESCRIPTION
**Pull request by rkh**
This PR makes Sinatra use [Mustermann](https://github.com/rkh/mustermann/blob/master/mustermann/README.md). It also updates the pattern to what I'd like the [Sinatra 2.0 syntax](https://github.com/rkh/mustermann/blob/master/mustermann/README.md#-sinatra-pattern) to be, it is generally compatible with [the old syntax](https://github.com/rkh/mustermann/blob/master/mustermann-simple/README.md).

This will also lead to more meaningful errors on broken patterns.

Advanced Mustermann features are not yet exposed.

### CODE REVIEW

**Comment by rkh** [comment]
Failing on JRuby atm.

**Comment by kgrz** [comment]
The tests are passing if I run one file at a time. I ran the `helpers_test` and `static_test`, and both pass on `jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]`

Is this because we are using a pre-release jRuby version for the test? I see this in travis logs:

`jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 +jit [linux-amd64]`

**Comment by zzak** [comment]
Build is green with latest JRuby (9.1.0.0)

**Comment by namusyaka** [comment]
Awesome :tada:

**Comment by kgrz** [comment]
:clap::clap::clap::clap:

**Comment by rkh** [comment]
🎉

**Comment by vipulnsward** [comment]
🚀

**Comment by namusyaka** [comment]
@rkh Should we move mustermann from your personal project to Sinatra organization?

**Comment by rkh** [comment]
@namusyaka done

**Comment by namusyaka** [comment]
@rkh Great! Thank you!

**Pull request merged**
