### PR TITLE
Add @ag_dubs to sinatra-core :clap: :tada: :confetti_ball: :tada:

### PR DESCRIPTION
**Pull request by zzak**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yay! Welcome.

**Comment by zzak** [comment]
> Added! :) ❤️💖💙💕💛💜💚

screen shot 2015-06-20 at 11 38 31 am

Congrats @ashleygwilliams and welcome!! <3

**Comment by namusyaka** [comment]
:tada::tada::tada:

**Comment by arthurvr** [comment]
Awesome news! Congrats @ashleygwilliams!

**Comment by ferdinandrosario** [comment]
congrats :clap: :tada: :tada:

**Pull request merged**
