### PR TITLE
break: Drop "Less" templating support

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR **removes the support** for the defunct **Less templating library**, and **removes** the **therubyracer** dependency, which was used to run tests for it.

See #1716, #1715 for more discussion and background.

## Details

This will get us to the position where Ruby 3.1 (ruby-head) can install, but has some failing tests (unrelated to the Less templating library, and to therubyracer gem.)

## TODO:

- [x] Remove "less" from READMEs

### CODE REVIEW

**Review by epergo — APPROVED** [review]
Nice! Since this PR could be considered a breaking change, should we merge into the `unstable` branch?

**Comment by olleolleolle** [comment]
@epergo Is there more than master and stable?

**Comment by olleolleolle** [comment]
@zzak 👋 I hope this fits the "unstable" branch.

**Comment by todd-a-jacobs** [comment]
I looked through the results when tested against ruby-head, and don't entirely understand why the tests are failing. One looks like a Nokogiri issue where [there's a missing trailing `]` in the output](https://github.com/sinatra/sinatra/pull/1718/checks?check_run_id=3444340092#step:5:150), but the others seem like they're related to Content-Length issues, which means something in ruby-head is likely changing the behavior of #mock-app or #body.

Is a failure of this sort against ruby-head (which isn't stable anyway) a reason not to merge the changes?

**Comment by jkowens** [comment]
@olleolleolle would you mind resolving these conflicts and we'll get this merged 👍

**Comment by olleolleolle** [comment]
@jkowens Thanks for letting me know!

**Comment by olleolleolle** [comment]
I made an abortive attempt using a formatting-happy solargraph'd vim installation, and then I decided to try the GitHub resolution tool. I'll make a try rebasing the branch now, that the conflict is resolved.

**Comment by olleolleolle** [comment]
@jkowens Thanks a lot for moving forward on this!

**Pull request merged**
