### PR TITLE
Capture bodies of raised NotFound and BadRequest exceptions

### PR DESCRIPTION
**Pull request by mwpastore**

### CODE REVIEW

**Comment by zzak** [comment]
@mwpastore Could you rebase please?

**Comment by zzak** [comment]
cc #1216

**Comment by mwpastore** [comment]
@zzak I've noticed that we are reimplementing a lot of Rack::Response in Sinatra::Base::Helpers. Can we use the delegation pattern to clean this up? Take a look at what I've done here. We can remove a bunch of tests, too, if we think this is a good idea.

**Comment by zzak** [comment]
@mwpastore I'm not against using delegators but this close to a release -- I want to make sure this won't affect any behavior or have performance impact.

With that said, something like this could be investigated after the release is made.

**Comment by mwpastore** [comment]
Okay, I pulled the gnarly stuff out into a separate branch for later perusal and brought this PR back to its original purpose. Let me know if you want to see any other changes!

**Comment by zzak** [comment]
For a second, I thought "body" was the body of the request, which would probably not be a good idea to print.

So can you change the wording from "body" -> "exception message"?

**Comment by mwpastore** [comment]
How's that?

**Pull request merged**
