### PR TITLE
French readme

### PR DESCRIPTION
**Pull request by mig-hub**
Hello,

I never really maintained this translation since I first created it, so I decided to proceed to a full review and fix as many things as possible. Each commit contains only one kind of modification (typos, grammar...) just in case they need to be filtered.

Cheers,
mig

### CODE REVIEW

**Comment by kytrinyx** [comment]
Oh, wow, this is great, thank you! Would you mind squashing the commits--I think this works well as a single change like _Overhaul French README_ or something to that effect.

**Comment by mig-hub** [comment]
Okay, I squashed them.
Thank you.

mig

**Comment by kytrinyx** [comment]
Thanks!

**Comment by mig-hub** [comment]
Sorry @kytrinyx but I also noticed something which looks like an error in all READMEs, but I'd like to check with you before making a pull request.

I think the line 1123 in the README is supposed to refer to the `:layout` option, not the `:template` option.

> A layout is usually just a template that calls `yield`. Such a template can be used either through the `:template` option as described above, or it can be rendered with a block as follows:

**Pull request merged**
