### PR TITLE
Require correct rack/show_exceptions file

### PR DESCRIPTION
**Pull request by djsegal**
Solves: https://github.com/sinatra/sinatra/issues/1055

--------

*Note*: Rack version was bumped to allow my Rails 5 app to work

### CODE REVIEW

**Comment by djsegal** [comment]
Sorry to lump several fixes together, but this also fixes:

+ Update `Content-Length` to use native string bytesize method
+ Use `file.serving request, path` when `file.path=` is not defined

// this was all done to get my rails 5 app to work with sidekiq (which it does now)

**Comment by djsegal** [comment]
Tests pass locally for me. How would one go about fixing this broken test?

```
  1) Error:
ServerTest#test_falls_back_on_the_next_server_handler_when_not_found_0:
ArgumentError: wrong number of arguments (2 for 1)
    /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rack-1.6.4/lib/rack/handler.rb:22:in `const_get'
    /home/travis/.rvm/gems/ruby-1.8.7-p374/gems/rack-1.6.4/lib/rack/handler.rb:22:in `get'
    /home/travis/build/sinatra/sinatra/lib/sinatra/base.rb:1785:in `detect_rack_handler'
    /home/travis/build/sinatra/sinatra/lib/sinatra/base.rb:1783:in `each'
    /home/travis/build/sinatra/sinatra/lib/sinatra/base.rb:1783:in `detect_rack_handler'
    /home/travis/build/sinatra/sinatra/lib/sinatra/base.rb:1453:in `run!'
    /home/travis/build/sinatra/sinatra/test/server_test.rb:54:in `test_falls_back_on_the_next_server_handler_when_not_found_0'
```

**Comment by kgrz** [comment]
I don't see a way other than removing support for 1.8.x. But doing that would mean a major bump in version. There is a [2.0 branch in the works](https://github.com/sinatra/sinatra/pull/1033) that addresses most of these issues including bumping up the rack version to > 2.0

**Comment by djsegal** [comment]
@kgrz you're right. i'm closing this PR. problems been resolved by https://github.com/sinatra/sinatra/pull/1033

**Comment by morgoth** [comment]
I run into the same issue.
When do you think it will be ready? Rails 5.0 is around the corner which depends on rack > 2.0, thus it's impossible to use sinatra with rails 5 apps currently. (I'm using it through sidekiq web ui)

**Comment by kgrz** [comment]
No fixed date as of now, although it's mostly ready. For now, one alternative is to use:

    gem 'sinatra', github: 'sinatra/sinatra', branch: '2.2.0-alpha'

or

    gem 'sinatra', github: 'kgrz/sinatra', branch: 'use-rack-files-serving-method'

in your Gemfile.

**Pull request closed without merging**
