### PR TITLE
Update and polish the Chinese translation (README.zh.md)

### PR DESCRIPTION
**Pull request by fighterleslie**
The original Chinese translation was rather outdated. This pull request aims at updating it to comply with the current English version (README.md). Many sentences are also rephrased to improve readability.

### CODE REVIEW

**Comment by codeworm96** [comment]
Great work! But there are some little problems:
1. Some links in the Table of Contents are broken
2. Some headings in the '可选的模板语言' section are not translated
Could you fix these problem?

**Comment by kgrz** [comment]
@fighterleslie There also have been some updates to the URL in general across the entire README.md (via #1072) Would be great if you could go through necessary changes based on it.

**Comment by fighterleslie** [comment]
Hi @codeworm96 Thanks for the review. :smile: 

> Some links in the Table of Contents are broken

Broken links in TOC have been fixed and tested.

> Some headings in the '可选的模板语言' section are not translated

Translated.

> Markdown style breaks near the '可选的设置' section

Fixed.

@kgrz URLs have been updated as per #1072

**Comment by codeworm96** [comment]
@fighterleslie Well done.

**Pull request merged**
