### PR TITLE
remove the roll your own part of docs

### PR DESCRIPTION
**Pull request by burningTyger**
This part is very specific and probably never used. If you're new to sinatra this shouldn't be kept in the Readme.

### CODE REVIEW

**Comment by zzak** [comment]
Good idea, does this exist in the other lang readmes?

**Comment by burningTyger** [comment]
Yes, I could remove it from the other Readmes as well. What about outdated Readmes? Should we retire some that haven't seen any love for more than two years?

**Comment by zzak** [comment]
I'm not sure which ones are considered out of date, happy to open up some tickets to find maintainer/contributor for the respective translations, and in the meantime put a note at the top of (potentially unmaintained) ones pointing to that ticket.

**Comment by davydovanton** [comment]
hey, I can help with Russian readme 👍

**Comment by burningTyger** [comment]
This is slightly embarrasing as I pushed an empty branch – now the pr is gone and GH doesn't update to the new commit. Maybe it'll work again. Otherwise the diff is here: https://github.com/sinatra/sinatra/compare/sinatra:master...burningTyger:remove_some_docs

**Pull request merged**
