### PR TITLE
Bump Rack to 1.5.x, but not 1.6 since it doesn't work on 1.8.7:

### PR DESCRIPTION
**Pull request by zzak**
https://travis-ci.org/sinatra/sinatra/jobs/67398284#L155

/cc #1009 #1010 @TrevorBramble @kytrinyx @rkh

### CODE REVIEW

**Comment by zzak** [comment]
If we can get rack/rack#901 released, we can remove `'< 1.6'`.

**Comment by ashleygwilliams** [comment]
:dancers:

**Comment by TrevorBramble** [comment]
Awesome. Reverted to 1.5 locally but hadn't updated the PR yet due to the other failing test (Rack 1.4).

**Comment by kytrinyx** [comment]
This looks good to me. Good to merge?

**Comment by TrevorBramble** [comment]
@kytrinyx afaik, yeah.

**Comment by zzak** [comment]
After the next rack 1.6.x bug-fix release, we can re-add support for that branch

**Comment by zzak** [comment]
I implemented a workaround in #1080 just FYI

**Pull request merged**
