### PR TITLE
Fix incorrect documentation for Sinatra::IndifferentHash

### LINKED ISSUE #1948: Sinatra::IndifferentHash does not support initialization with any hash or key-value pair list
In short, the following snippet from https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html does not work:

```rb
hash = ActiveSupport::HashWithIndifferentAccess.new(a: 1) # => {"a"=>1}
hash.keys # => ["a"]
```

Instead, this is what happens with `Sinatra::IndifferentHash`:

```rb
hash = Sinatra::IndifferentHash.new(a: 1) # => {}
hash.keys # => []
```

### PR DESCRIPTION
**Pull request by jkowens**
Resolves #1948. Looking over the code, I'm not sure that the `initialize` method makes sense to me.

```
    def initialize(*args)
      args.map!(&method(:convert_value))
      super(*args)
    end
 ```
 
 I don't know why you'd want to call `convert_value` on a value that's been specified as a default value when a key is missing. See https://ruby-doc.org/3.2.2/Hash.html#method-c-new

```
h = Sinatra::IndifferentHash.new(a: 1)
h[:b] = {"a" => 1 }
```

I'm thinking maybe that should be removed to eliminate possible confusion?

### CODE REVIEW

**Review by dentarg — APPROVED** [review]

**Comment by jkowens** [comment]
@dentarg what do you think about the argument conversion that happens in the initializer? I think it may be a source of confusion. Should we remove it in v4?

**Comment by olleolleolle** [comment]
> @dentarg what do you think about the argument conversion that happens in the initializer? I think it may be a source of confusion. Should we remove it in v4?

This conversion, is it done due to the design assumption "this should be used for taking an argument from querystring and landing it in an indifferent hash"?

**Comment by dentarg** [comment]
I can't make sense of the initializer... And I'm not sure I follow what @olleolleolle wrote, can you show some code examples using it?

(With my current knowledge, I think it is a good idea to remove it for v4)

**Comment by dentarg** [comment]
> Perhaps we can pair on making a test case where we explain the "why" of a conversion?

Oh I did not see this part of your reply (as it was added in an edit) – feel free to chip in at https://github.com/sinatra/sinatra/issues/1953 – I tried again now to understand why it would be useful, but I can't come up with anything

**Pull request merged**
