### PR TITLE
3.0.6 release

### PR DESCRIPTION
**Pull request by dentarg**
https://github.com/sinatra/sinatra/compare/v3.0.5...main

WDYT @sinatra/sinatras-helpers ?

Close https://github.com/sinatra/sinatra/issues/1882

### CODE REVIEW

**Comment by dentarg** [comment]
Or should it be 3.0.6? Not sure how to judge `New: Add support to keep open streaming connections with Puma`

**Comment by dentarg** [comment]
That could probably be `Fix` instead of `New`?

**Comment by jkowens** [comment]
@dentarg yeah I think you're right, this would be fine as a 3.0.6 release.

**Review by jkowens — APPROVED** [review]
Looks good, thank you @dentarg!

**Comment by olleolleolle** [comment]
Nice!

**Review by zzak — APPROVED** [review]

**Comment by jkowens** [comment]
@dentarg it looks like you should be able to cut a release to rubygems. Are you all good to do that?

**Comment by dentarg** [comment]
I'm gonna study the rake tasks before I do it :) Hope to get to it later in the week.

**Comment by dentarg** [comment]
@jkowens @zzak Looks like I didn't get access 😬 😇 Do you mind giving it again?

**Comment by jkowens** [comment]
@dentarg I see you in pending status for these gems. Did you get an email invitation?

**Comment by dentarg** [comment]
@jkowens got it!

**Comment by zzak** [comment]
@dentarg There is a guide here, hopefully it helps! Feel free to modify it and the process to your liking:
https://github.com/sinatra/sinatra/blob/main/RELEASING.md

Thanks for your contribution and congrats on your first release!

**Comment by dentarg** [comment]
Yeah the `git push` in the release task wont work with our protected `main` branch (maybe what caused https://github.com/sinatra/sinatra/issues/1882?)

https://github.com/sinatra/sinatra/blob/fb76534810a1b3d6365eb8e2296bf627cfbef8de/Rakefile#L194-L211

Good thing this branch has done the necessary changes :) I'll merge and build and push the packages

**Comment by olleolleolle** [comment]
@dentarg THANK YOU for pushing this!

**Pull request merged**
