### PR TITLE
Default IndifferentHash keys to Symbols instead of Strings

### LINKED ISSUE #1592: params can't be used as keyword arguments
We can't pass `params` hash and expect keyword args to be matched because of the current `IndifferentHash` implementation.

```ruby	
def a(a:, **); end
a(Hash[a: 1]) # => nil
a(Sinatra::IndifferentHash[a: 1]) # => ArgumentError (wrong number of arguments (given 1, expected 0; required keyword: a))
a(**Sinatra::IndifferentHash[a: 1]) # => TypeError (hash key "a" is not a Symbol)
```

Changing the `IndifferentHash` private method `convert_key` to always return `key.to_s.to_sym` solves this.

### PR DESCRIPTION
**Pull request by baelter**
.. so it works with keyword args works as expected.

Fixes #1592

### CODE REVIEW

**Comment by dentarg** [comment]
I guess the docs need to be updated?

https://github.com/sinatra/sinatra/blob/623a80ba6a5e1d52092480466c880ed0b02e2ca8/lib/sinatra/indifferent_hash.rb#L27-L29

**Comment by baelter** [comment]
Perhaps "You are guaranteed that the key is returned as a string" should be changed to "You are guaranteed that the key is returned as a symbol" for consistency? But I figured that's more of a breaking change.

**Comment by dentarg** [comment]
Sounds like a breaking change to me :)

Is there any performance gain/regression happening with this change?

I wonder what our maintainers (@jkowens @namusyaka @olleolleolle and probably others) think of this change?

**Comment by jkowens** [comment]
This issue has also been brought up in the Rails project. Since this models `ActiveSupport::HashWithIndifferentAccess` I would like to stay in line with the approach there. I'm wondering if we can also provide a method `symbolize_keys` that will serve as a work around. 

See: 

https://github.com/rails/rails/issues/14643

https://bugs.ruby-lang.org/issues/9731

https://til.hashrocket.com/posts/d66e55091c-hashwithindifferentaccess-for-keyword-arguments

**Pull request closed without merging**
