### PR TITLE
correction in Portuguese Brazil

### PR DESCRIPTION
**Pull request by hemershon**
I made some changes to the Portuguese BR, over the days I will correct more.

### CODE REVIEW

**Comment by jkowens** [comment]
Thanks! There was quite a bit started in PR #1497 but never completed. Would you possibly be able to pull in some of those updates?

**Comment by jkowens** [comment]
Here's another PR that needs carried across the finish line if you're interested 😉 

#1523

**Comment by hemershon** [comment]
it will be a pleasure to continue with these translations.

I will continue with PR #1497  and #1523 


> Thanks! There was quite a bit started in PR #1497 but never completed. Would you possibly be able to pull in some of those updates?

**Comment by hemershon** [comment]
it will be a pleasure to continue with these translations.

> Here's another PR that needs carried across the finish line if you're interested 
> 
> #1523

Okay, I already realized that this is a situation that has to be taken seriously, you can count on me to continue with the translations and something.

**Pull request merged**
