### PR TITLE
Small CI improvements

### PR DESCRIPTION
**Pull request by walro**
* Disable `fast-fail` so that we can feedback for all versions in the matrix, even if a specific version fails
* Run the test workflow for all branches, this is useful when you want test feedback without having to open a PR

### CODE REVIEW

**Comment by epergo** [comment]
> Run the test workflow for all branches, this is useful when you want test feedback without having to open a PR

Not sure about this but, isn't that option only valid for this repository? So only people with push rights here could benefit from it.

**Comment by walro** [comment]
> Not sure about this but, isn't that option only valid for this repository?

I think it's correct. Prior to the change, pushing a branch on a forked repository wouldn't trigger the test workflow.

**Comment by walro** [comment]
I tested:

* A commit in a branch based on current master: https://github.com/walro/sinatra/commit/e0eb1b5736217bf196364b1946638c090855af92 (no workflow runs)
* A commit in a branch based on this PR: https://github.com/walro/sinatra/commit/5a8b5d9b41a651e5bc5aea0b2bac375f5b0a85fa (workflow runs)

**Comment by epergo** [comment]
You are right! Thanks for the explanation 🙇‍♂️

**Comment by walro** [comment]
Ah [continue-on-error](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) for a job still reports back failed status (I should have noticed this in my fork, sorry! 🤦). Have to change to the [step scoped version](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) but seeing we fail quite early, while installing gems, for `ruby-head` I am not entirely sure how to structure it right now.

Meanwhile, I will drop the commits regarding `continue-on-error` here and see if I can come up with something better for allow failures.

**Review by epergo — APPROVED** [review]

**Pull request merged**
