### PR TITLE
No need to specify Ruby patch version on Travis CI

### PR DESCRIPTION
**Pull request by iguchi1124**
Travis CI selects latest patch version when we given MAJOR and MINOR version number.
And I removed patch version number for not latest minor version ruby.

What do you think about this?

### CODE REVIEW

**Comment by dentarg** [comment]
> Travis CI selects latest patch version when we given MAJOR and MINOR version number

Doesn't seem to work well in practice, for Ruby 2.4 it looks like the tests now run 2.4.1: https://travis-ci.org/sinatra/sinatra/jobs/393608170#L554

**Comment by olleolleolle** [comment]
Here's my understanding of why this happens the way it happens:

- Travis CI uses `rvm`
- The `rvm` installed knows about a list of versions
- If given a version pattern it does not know about, such as `2.4.3`, it'll go look for it online
- If given a "version alias" such as `2.4`, it'll use it without checking online for newer versions

**Comment by dentarg** [comment]
Seems to be know issue: https://github.com/travis-ci/travis-ci/issues/9559

**Comment by junaruga** [comment]
Why not using "2.5" instead of "2.5.1"?

**Comment by olleolleolle** [comment]
@junaruga Because then we're at the mercy of what versions are currently supported in  by those short aliases in`rvm`.

**Comment by namusyaka** [comment]
Travis ci seems not to use latest ruby version without patch version.
I'm not going to merge this until resolving the issue.

**Pull request closed without merging**
