### PR TITLE
Revert "Sinatra::Contrib dependency updates. Fixes #1207"

### LINKED ISSUE #1207: Remove backports dependency from sinatra-contrib
Now that the minimum Ruby version is 2.2 (.2 due to Rack 2), can we remove sinatra-contrib's dependency on backports? Tests pass on 2.2.2 without it with some light refactoring around String#underscore and Object#try. 

Why is Rack::Test a runtime dependency and not a development dependency?

I've submitted a PR with these changes but wanted to see what "tribal knowledge" might be out there.

### PR DESCRIPTION
**Pull request by namusyaka**
Reverts sinatra/sinatra#1208

### CODE REVIEW

**Comment by marcandre** [comment]
Hi! What is the purpose of this PR?
(`backports` author here...)
Please avoid calling `require 'backports'`  and instead require the needed backports individually.
In the case of Sinatra, I don't think there are any being used though.

**Comment by namusyaka** [comment]
@marcandre The purpose of this PR is to revert #1208 as described.
As a matter of fact, you can say that your point is correct, but I think that you should rollback this change according to git's workflow.

**Comment by marcandre** [comment]
`try` and `underscore` are not really backports, they are part of `ActiveSupport`
Would you consider instead requiring them from `ActiveSupport` instead? Having those in `backports` was a mistake, even when they used to not be available independently.

Otherwise, at the very least, do not require the whole suite of backports, but just those that are required. I can provide a PR if need be.

**Comment by dentarg** [comment]
@namusyaka what was the reason to revert #1208?

**Comment by namusyaka** [comment]
@dentarg See https://github.com/sinatra/sinatra/pull/1208#discussion_r175315055
The change potentially breaks backward compatibility.

**Pull request merged**
