### PR TITLE
Failing helper overload spec

### PR DESCRIPTION
**Pull request by baelter**

### CODE REVIEW

**Comment by jkowens** [comment]
It doesn't look like this spec is failing, can you double check this? Thank you for working on this, a failing spec will be very helpful.

**Comment by baelter** [comment]
File had wrong name...

**Comment by jkowens** [comment]
@namusyaka do you have any thoughts on this? Should we plan on reverting the change in #1213?

**Comment by namusyaka** [comment]
@jkowens Yes, we should revert the change, it shouldn't be merged into v2.1.0 (probably v3.0.0 seems good).

**Comment by namusyaka** [comment]
Merged in #1662 , thanks.

**Pull request closed without merging**
