### PR TITLE
Remove "WEBrick does not support streaming"

### PR DESCRIPTION
**Pull request by drbrain**
WEBrick supports streaming responses since before it was imported into
ruby 1.8.0, probably since it was written.

If Sinatra doesn't support streaming with WEBrick it is a bug in Sinatra
or rack and should be described that way explicitly.

Thanks to @tenderlove for help with the README.ja.md.  All others were
checked in google translate.

### CODE REVIEW

**Comment by zzak** [comment]
Thank you!

I haven't tried streaming w/ WEBrick to be honest.. but if there's a bug we should try to fix it.

**Comment by drbrain** [comment]
The current description implies that WEBrick is missing the freatures necessary to support streaming (chunked transfer-encoding).

WEBrick has this feature, so it seems the appropriate adaper has not yet been written.

If you wish to speak about how Sinatra can't stream a response using WEBrick it should be written to point blame at the appropriate party.

**Comment by zzak** [comment]
I'm not interested in pointing any blame, but if there's a bug which prevents Sinatra from streaming with WEBrick I would like to fix it.

**Comment by rkh** [comment]
This was never meant to put blame on WEBrick, apologies for the poor phrasing.

The WEBrick Rack handler for the longest time did not support streaming in the sense that content could be sent out while other content is still being generated.

**Comment by zzak** [comment]
LGTM

**Pull request merged**
