### PR TITLE
Use prepend instead of include for helpers. Fixes #1213

### LINKED ISSUE #1213: Inconsistent overriding of previously-defined helpers
There's a slight inconsistency with the order in which Sinatra applies helpers when those helpers may have been previously defined. This is probably best explained with an example:

```ruby
module HelperOne
  def one; '1' end
end

class MockApp < Sinatra::Base
  helpers do
    def one; nil end
    def two; nil end
  end

  helpers ::HelperOne do
    def two; '2' end
  end

  get('/one') { one }
  get('/two') { two }
end
```

One might reasonably expect one of two outcomes from the above:

1. `/one` returns `"1"` and `/two` returns `"2"` (i.e. the later-defined helpers override the previously-defined helpers)
2. `/one` returns `nil` and `/two` returns `nil` (i.e. the previously-defined helpers are "sticky" and cannot be overridden)

But what actually happens is:

3. `/one` returns `nil` and `/two` returns `"2"`

So previously-defined helpers can be overridden in the block, but not in an included helpers module. This is inconsistent and confusing. To fix it, let's `prepend` the module(s) instead of `include`-ing them.

### PR DESCRIPTION
**Pull request by mwpastore**

### CODE REVIEW

**Comment by zzak** [comment]
See my comment on #1213

**Comment by mwpastore** [comment]
I did. 😄 This can wait. My only counterargument would be that there's never going to be a better time to break things, so if this makes sense, let's do it. The counterargument to _that_ is that 2.0's already been in pre-release for ages and cramming things in at the end of the cycle isn't kosher. Anyway, I'm fine waiting, and if you are feeling like you'll never want to merge it, that's fine too.

**Comment by zzak** [comment]
@mwpastore Please wait :bow:

**Comment by baelter** [comment]
Ouch, this broke a lot of things. Helpers are not overloaded like before.

**Comment by aldentea** [comment]
Yes. If a helper module uses included method, it doesn't work.

**Comment by jkowens** [comment]
Hm not good. @baelter / @aldentea would you be able to submit a PR with a failing test?

**Comment by baelter** [comment]
@jkowens 
Here you go, this works in v2.0.8.1
https://github.com/baelter/sinatra/commit/53f741c4ec3d3a82c013198152a3710aec2545f7

**Comment by baelter** [comment]
Could use `prepend(Module.new(&block))` instead of `class_eval(&block)` but then that does not play nice with `alias_method`. I don't think it's possible to combine `prepend` and `alias_method`.

**Pull request merged**
