### PR TITLE
Update German README

### PR DESCRIPTION
**Pull request by burningTyger**
Don't pull yet, I'll post further translations and then squash the commits into one or two commits.

I'll post my updates to the German README here as it progresses. There have been quite a few changes throughout the months.

Wer mithelfen möchte, kann dies gerne tun, das Dokument lässt sich ja problemlos aufteilen.

### CODE REVIEW

**Comment by burningTyger** [comment]
ouch, forgot the skip. 

Status: line 1115 ### Accessing Variables in Templates

**Comment by burningTyger** [comment]
ok, finished my update. If someone wants to check my spelling you're more than welcome.

I also changed some stuff in the English readme:
* spelling mistakes like its -> it's
* line width reduced to 80 (yes, I need 80 because I'm translating side by side in vim)
* indented some of the dds for better readability
* changed some of the examples to make it look less old (2012 -> 2016, or a rails 3.0 requirement)
* and so on

**Comment by zzak** [comment]
@burningTyger Is this ok?

**Comment by burningTyger** [comment]
@zzak I will read it again this afternoon and may add the latest addition (mustermann changes) to it. Otherwise it's ok.

**Comment by burningTyger** [comment]
@zzak I've double checked spelling etc and the German version is now up to date with the English version.

**Comment by zzak** [comment]
Thank you @burningTyger!

**Pull request merged**
