### PR TITLE
Fix additional Ruby 2.7 keyword warnings

### PR DESCRIPTION
**Pull request by stefansundin**
These were missed in https://github.com/sinatra/sinatra/pull/1581.

### CODE REVIEW

**Comment by namusyaka** [comment]
If you hope eliminating the warnings, why didn't you fix other points such as "send_file"?

**Comment by namusyaka** [comment]
Also, AFAIK, the "opt = {}" with keyword args will be kept as compatibility layer as per https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign#compatibility-layer

So I guess we don't have to merge this for v2.7, right?

**Comment by stefansundin** [comment]
I got the warnings from `sinatra/reloader` when loading my app in dev mode. I was curious, so I tried to require all the sintra-contrib files, and the only other one that gave me a warning was `sinatra/respond_with`.

I don't know why the other methods with `options = {}` don't trigger the warning, but these three definitely do. As for why I didn't fix `send_file`, I don't think it requires fixing. Please double check this though.

And like that other PR that is already merged, this isn't strictly required, it just prints an annoying warning when the files are included with `require`.

**Comment by namusyaka** [comment]
@stefansundin Thanks.

@jkowens Could you check in term of other perspective?
Also I would like you to check the thing I pointed out (e.g. `send_file`).

**Comment by stefansundin** [comment]
@jkowens Could you take a look at this? I think we can merge it. Thanks!

**Comment by jkowens** [comment]
@stefansundin I found two more locations that are throwing warnings when I run the tests. Can you fix those as well? 🙏 

https://github.com/sinatra/sinatra/blob/2527f46bc4cbe3bffedc2a2658e8d737eaa5908b/lib/sinatra/base.rb#L1526

https://github.com/sinatra/sinatra/blob/2527f46bc4cbe3bffedc2a2658e8d737eaa5908b/sinatra-contrib/lib/sinatra/namespace.rb#L335

**Comment by stefansundin** [comment]
Hi @jkowens. I'm having issues installing libv8 on my machine, so I can't test it unfortunately. Could you tell me exactly what to change those two lines to?

I think you can also propose the exact changes in a review: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request

And since you are a member of the Sinatra org, I think you have write access already to this branch. Feel free to push to it yourself.

**Comment by jkowens** [comment]
Ok, I ended up only updating one other location. The warning at `sinatra/base.rb#L1526` seems like it will need to be addressed by the rack handlers (Puma, etc).

**Pull request merged**
