### PR TITLE
Fix broken origin_whitelist option #1641

### PR DESCRIPTION
**Pull request by takeshi-yashiro**
This PR fixes bug #1641

### CODE REVIEW

**Comment by jkowens** [comment]
Looks good, thanks!

@namusyaka would you be able to cut a patch release with this fix?

**Comment by namusyaka** [comment]
Before cutting a new patch release, I would love to automate the process. I don't want to cut a new release manually again and again.

**Comment by namusyaka** [comment]
ref #1515 #1510

**Review by namusyaka — APPROVED** [review]
Thanks!

**Comment by kmiller-stripe** [comment]
@namusyaka / @jkowens  I completely understand the wanting to automate the process, so if that's still a work in progress then great!

This has been merged for nearly a year though, so I'm wondering if there's any plans on cutting a release with this change?

**Comment by jkowens** [comment]
@kmiller-stripe I'm disheartened with the state of Sinatra as well. I am not able to cut releases, I hope we see one sometime soon.

cc: @sinatra/sinatras-helpers

**Pull request merged**
