### PR TITLE
Use Sinatra::Runner In Integration Test

### PR DESCRIPTION
**Pull request by apotonick**
As per PR https://github.com/sinatra/sinatra-contrib/pull/122 we now use `Sinatra::Runner` for integration tests.

Only problem is that we have a development dependency to `sinatra-contrib` but @rkh promised to look into that.

### CODE REVIEW

**Comment by zzak** [comment]
We can merge this once it is rebased, and `sinatra-contrib` is updated to support Sinatra master branch

**Comment by zzak** [comment]
Rebased and fixed in 80016d74185a202f672b1ce5a9b8622cfb7a5f11

**Comment by apotonick** [comment]
:kiss:

**Comment by zzak** [comment]
@apotonick <3

**Pull request closed without merging**
