### PR TITLE
avoid executing filters even if prefix matched with other namespace

### LINKED ISSUE #1251: Sinatra::Namespace nesting similarly-named namespaces
Still trying to wrap my brain around this but wanted to get an issue going for feedback, particularly from @zzak since he rewrote Sinatra::Namespace for 2.0 and is hopefully familiar with its inner-workings. 😄 

Take the following sample application:

```ruby
require 'sinatra/base'
require 'sinatra/namespace'

class MyApp < Sinatra::Base
  register Sinatra::Namespace

  helpers do
    def dump_args(*args)
      args.inspect
    end
  end

  namespace '/foo' do
    helpers do
      def dump_args(*args)
        super(:foo, *args)
      end
    end

    get '' do
      "#{dump_args}\n"
    end
  end

  namespace '/foo-bar' do
    helpers do
      def dump_args(*args)
        super(:foo_bar, *args)
      end
    end

    get '' do
      "#{dump_args}\n"
    end
  end

  run! if $0 == __FILE__
end
```

Expected output:

```console
$ curl localhost:4567/foo
[:foo]
$ curl localhost:4567/foo-bar
[:foo_bar]
```

> Summary: The `super` of each namespace's `dump_args` helper is expected to be the `dump_args` helper defined in the parent application.

Actual output:

```console
$ curl localhost:4567/foo
[:foo]
$ curl localhost:4567/foo-bar
[:foo, :foo_bar]
```

> Summary: The `super` of the second namespace's `dump_args` helper is the `dump_args` helper defined in the first namespace.

Although the two routes are in two separate namespaces, and hence, ostensibly, in two separate modules, it appears as though the latter is nested under the former. This only happens when the longer route starts with the same string as the shorter route; i.e. if the second namespace were named simply `/bar`, this issue would not manifest. 

I can confirm this issue is present in Sinatra 1.4.8 (with and without Mustermann), 2.0.0.beta2, and master tip.

### PR DESCRIPTION
**Pull request by namusyaka**
Fixes #1251 

@mwpastore @zzak Could you confirm this?

### CODE REVIEW

**Comment by zzak** [comment]
Thank you @namusyaka, I'm happy to merge this but will wait for @mwpastore's seal of approval ;)

**Comment by namusyaka** [comment]
Any progress on this?

**Comment by namusyaka** [comment]
@mwpastore Could you check about this?

**Comment by mwpastore** [comment]
Hi @namusyaka, I pinged you on the Slack about this, but I guess you didn't see it. I'm getting hung up on this because I don't really understand the solution. Can you help me understand the why and how? That being said, my review is superfluous if it solves the problem.

**Comment by namusyaka** [comment]
@mwpastore @zzak Sorry for the late reply.
I will explain the issue.

The sinatra namespace is prefixed to verb and filter methods (see https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/namespace.rb#L232) by using original methods of indivisual namespaces.
The prefix rule is defined in [this line](https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/namespace.rb#L335), but the filter is a special one [using the constant regexp](https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/namespace.rb#L336).
Root of your issue is here.

Please take a look at [these lines](https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/namespace.rb#L321-L324).
The before filter is registered with the regexp and the prefix for the namespace.
`prefixed_path` will make the concat pattern which is something like:

```ruby
require 'mustermann'

# These vars are prefix of namespace.
foo     = Mustermann.new('/foo')
foo_bar = Mustermann.new('/foo-bar')

# current pattern
regexp = Mustermann.new(/.*/)

p (foo_bar + regexp) === '/foo-bar' #=> true
p (foo + regexp) === '/foo-bar'     #=> true (but expected to return false)

##############################################

# my patch
regexp = Mustermann.new(%r{(?:/.*)?})

p (foo_bar + regexp) === '/foo-bar' #=> true
p (foo + regexp) === '/foo-bar'     #=> false
```

Under the above principle, even filter which does not expect to operate originally has been executed.
Thus, your issue has been occured by [calling twice `extend` method](https://github.com/sinatra/sinatra/blob/master/sinatra-contrib/lib/sinatra/namespace.rb#L199).

**Comment by namusyaka** [comment]
So my patch makes it avoid the unexpected matching with filter. I guess this is reasonable. Thoughts?

**Comment by zzak** [comment]
Because this patch affects namespace, which was changed in 2.0 to support Mustermann, we are fine to merge it.

Thank you @namusyaka for your patch and explanation!

**Comment by mwpastore** [comment]
Thank you for the patch and the explanation, @namusyaka, and thank you both for your patience! 🙇

**Pull request merged**
