### PR TITLE
Fixed 'warning: possible reference to past scope'

### PR DESCRIPTION
**Pull request by vipulnsward**
Fixed 'warning: possible reference to past scope' in static test, due to reusing similar variables in test contexts, by renaming the required variables.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks for looking into this. Is there a way to fix this without introducing (seemingly arbitrary) inconsistencies?

I know sometimes inconsistency is necessary, and sometimes it's probably even worth it, but I think that where possible if it's the same idea, it should have the same name.

**Comment by vipulnsward** [comment]
Nope. Ruby goes on to warn about it. Another way is to prefix re-definitions with '_' which keeps the usage idea relatively the same.

**Comment by kytrinyx** [comment]
Then we would end up with `body`, `_body`, and `__body`... which I don't find to be any better.

This is one of the reasons I prefer the `test` version of the framework over the `spec` version of it.

**Comment by mattwildig** [comment]
I’ve just has a look at this out of curiosity, and it seems like this warning has been removed from MRI Ruby: https://bugs.ruby-lang.org/issues/10661. Running the tests with ruby-head doesn’t produce this warning at all. It might not be worth doing anything with these for now.

**Comment by vipulnsward** [comment]
Thats awesome. Thanks @mattwildig !

**Comment by kytrinyx** [comment]
Thanks @mattwildig -- that's good to know!

**Pull request closed without merging**
