### PR TITLE
[rack-protection] Drop unused Travis config 

### PR DESCRIPTION
**Pull request by olleolleolle**
~~This PR updates the CI matrix to use latest JRuby.~~

~~http://jruby.org/2017/09/06/jruby-9-1-13-0.html~~

Drop unused config.

### CODE REVIEW

**Comment by zzak** [comment]
Actually think we don't use this file anymore so better to delete it

**Comment by olleolleolle** [comment]
@zzak There!

**Comment by olleolleolle** [comment]
Are there more config like this which has been left in the monorepo?

**Comment by olleolleolle** [comment]
Like, the `.rspec` defaults file inside there?

**Comment by zzak** [comment]
@olleolleolle Thanks!! As for other config, I'm not sure.

**Pull request merged**
