### PR TITLE
Add specs for Response#finish

### PR DESCRIPTION
**Pull request by ysksn**
1. With status code _205_, `Response#finish` will remove **Content-Type** and **body** as well.

2. Other than status code _204_, _205_, and _304_, `Response#finish` will not remove **Content-Type** and **body**.

### CODE REVIEW

**Comment by zzak** [comment]
Looks like CI is failing for other reasons, I will try to get to the bottom of it.

**Comment by ysksn** [comment]
@zzak I think CI has been been fixed #1125

**Comment by zzak** [comment]
@ysksn Looks green! Can you please squash your commits?

Thanks <3

**Comment by ysksn** [comment]
I hope it is right way to squash commits.
Let me know if I'm wrong.

Thanks
:)

**Comment by zzak** [comment]
[This blog post](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) has more info on how to squash, but based on your branch it should come down to:

1. `$ git rebase -i HEAD~7`
2. Replace commits 2-7 with "squash" instead of "pick"
3. Optionally do "reword" for the first commit (for full message)
4. `$ git push origin response --force`

Step 3 will take place in your editor, once you save and quit git will rebase your branch, then you will need to force push to your PR branch ("response") to update the pull request.

Let me know if you get stuck!

**Comment by zzak** [comment]
@ysksn I rebased your branch and pushed to a new PR #1127

**Pull request closed without merging**
