### PR TITLE
Add TruffleRuby to CI matrix

### PR DESCRIPTION
**Pull request by dentarg**

### CODE REVIEW

**Comment by dentarg** [comment]
Maybe @eregon can take a look here? As it now works with MRI and JRuby

**Comment by epergo** [comment]
Probably because almost every gem is under `RUBY_ENGINE == "ruby"` https://github.com/sinatra/sinatra/blob/master/Gemfile#L29 We have to update it so dependencies are installed for truffle

**Comment by eregon** [comment]
Right that line should probably be unconditional.

FWIW, `if RUBY_ENGINE` in Gemfile is kind of an anti-pattern, `gem 'foo', platforms: :ruby` can be used to specify a gem which needs C extensions and is not installed on JRuby & on Windows: https://bundler.io/man/gemfile.5.html#PLATFORMS

Rubinius is dead AFAIK so that could probably be removed entirely from the Gemfile.

**Comment by olleolleolle** [comment]
https://github.com/sinatra/sinatra/pull/1756 Thanks for the reminder, here is "drop rbx:.

**Comment by olleolleolle** [comment]
OK! #1757 is "use platforms:"!

**Comment by olleolleolle** [comment]
(Gotta rebase, then we'll know more!)

**Comment by jkowens** [comment]
@olleolleolle ah that's right. If I close/re-open the issue does that pick up the latest changes in master?

**Comment by olleolleolle** [comment]
> @olleolleolle ah that's right. If I close/re-open the PR does that pick up the latest changes in master?

@dentarg is probably awake enough to do that for us.

**Comment by eregon** [comment]
I commented on https://github.com/sinatra/sinatra/pull/1757 there are a few tweaks needed to let the gems install on TruffleRuby.

**Comment by eregon** [comment]
I (or maybe @bjfish) could take a shot e.g. tomorrow at making a PR changing whatever is needed (e.g., the Gemfile) to make the gems install correctly on truffleruby and the tests pass, that may be easier.

**Comment by olleolleolle** [comment]
(Thanks, dentarg!)

> /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo/timezone.rb:653:in `const_missing': uninitialized constant ThreadSafe::Cache (NameError)


<details>

```
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[ruby] WARNING: Encoding.find('locale') is US-ASCII, this often indicates that the system locale is not set properly. Set LANG=C and LC_ALL=C to suppress this warning (but some things might break).
/home/runner/.rubies/truffleruby-22.0.0.2/lib/patches/thread_safe.rb:3: warning: loading in progress, circular require considered harmful - /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/thread_safe-0.3.6/lib/thread_safe.rb
/home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo/timezone.rb:653:in `const_missing': uninitialized constant ThreadSafe::Cache (NameError)
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo/timezone.rb:653:in `init_loaded_zones'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo/timezone.rb:655:in `<class:Timezone>'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo/timezone.rb:46:in `<module:TZInfo>'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo/timezone.rb:5:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/tzinfo-1.2.9/lib/tzinfo.rb:31:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-5.1.7/lib/active_support/values/time_zone.rb:1:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-5.1.7/lib/active_support/core_ext/time/conversions.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-5.1.7/lib/active_support/core_ext/time/calculations.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-5.1.7/lib/active_support/core_ext/time.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-5.1.7/lib/active_support/time.rb:10:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-5.1.7/lib/active_support/core_ext/hash/conversions.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/test/helper.rb:34:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/test/asciidoctor_test.rb:1:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
/home/runner/.rubies/truffleruby-22.0.0.2/bin/bundle:42:in `<main>'
```

</details>

**Comment by olleolleolle** [comment]
Perhaps #1758 will make more gems available to Truffleruby?

**Comment by eregon** [comment]
`thread_safe` is deprecated since a while and never had TruffleRuby suport, unlike concurrent-ruby which works fine.
It seems to be tzinfo 1.2.9 depending on it:
```
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
```
Would it possible to update to a newer tzinfo which nowadays depends on concurrent-ruby? (https://github.com/tzinfo/tzinfo/blob/master/tzinfo.gemspec)

**Comment by olleolleolle** [comment]
@eregon Ah, yes, the venerable 

```
activesupport (5.1.7)
  concurrent-ruby (~> 1.0, >= 1.0.2)
  i18n (>= 0.7, < 2)
  minitest (~> 5.1)
  tzinfo (~> 1.1)

```

**Comment by olleolleolle** [comment]
@eregon Now, we have arrived somewhere more interesting, I _think_. Here is a fragment:

> /home/runner/.rubies/truffleruby-22.0.0.2/lib/patches/concurrent/atomic/atomic_reference.rb:8: warning: loading in progress, circular require considered harmful - gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/atomic/atomic_reference.rb
>  gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/configuration.rb:89:in `const_missing': uninitialized constant Concurrent::AtomicReference (NameError)
> 	from /gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/configuration.rb:89:in `<module:Concurrent>'
> 
> 

<details>

```
/home/runner/.rubies/truffleruby-22.0.0.2/lib/patches/concurrent/atomic/atomic_reference.rb:8: warning: loading in progress, circular require considered harmful - /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/atomic/atomic_reference.rb
/home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/configuration.rb:89:in `const_missing': uninitialized constant Concurrent::AtomicReference (NameError)
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/configuration.rb:89:in `<module:Concurrent>'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/configuration.rb:11:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent.rb:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-6.1.4.6/lib/active_support/logger_thread_safe_level.rb:5:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-6.1.4.6/lib/active_support/logger_silence.rb:5:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-6.1.4.6/lib/active_support/logger.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/activesupport-6.1.4.6/lib/active_support.rb:29:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rabl-0.15.0/lib/rabl.rb:1:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/test/rabl_test.rb:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
```

</details>

**Comment by eregon** [comment]
I could repro it locally, also with latest TruffleRuby, I filed https://github.com/oracle/truffleruby/issues/2605

**Comment by eregon** [comment]
BTW this warning:
```
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[ruby] WARNING: Encoding.find('locale') is US-ASCII, this often indicates that the system locale is not set properly. Set LANG=C and LC_ALL=C to suppress this warning (but some things might break).
```
is caused by:
https://github.com/sinatra/sinatra/blob/0309bbb9b28044bdde9f96ecae811f6534c7c851/Rakefile#L27-L28

It'd be great to remove that as that can break lots of things in very subtle ways (but doesn't seem the cause of the issue linked above).

**Comment by olleolleolle** [comment]
Speculating: Ah, is `rainbows` the gem, now not yet added with a `platforms:` including `:ruby`?

```
loading
starting
/home/runner/work/sinatra/sinatra/vendor/bundle/truffleruby/3.0.2.22.0.0/gems/rack-2.2.3/lib/rack/handler.rb:45:in `pick': Couldn't find handler for: rainbows. (LoadError)
	from /home/runner/work/sinatra/sinatra/lib/sinatra/base.rb:1489:in `run!'
	from /home/runner/work/sinatra/sinatra/lib/sinatra/main.rb:45:in `block in <module:Sinatra>'

```

**Comment by eregon** [comment]
I or @bjfish will take a look

**Pull request merged**
