### PR TITLE
Update CHANGELOG for 1.4.7

### PR DESCRIPTION
**Pull request by jaredbeck**
Mention rack 2 support in 1.4.7

[ci skip]

### CODE REVIEW

**Comment by zzak** [comment]
Can we still say it's supported when we only depend on 1.x in the gemspec?
https://github.com/sinatra/sinatra/blob/v1.4.7/sinatra.gemspec#L16

**Comment by kgrz** [comment]
Yeah, let's not say Rack 2 for 1.4.7. The LoadError issue is one part. The Rack::File related changes are not in 1.4.7, and may break it if used with Rack 2. cmiiw @TrevorBramble

**Comment by zzak** [comment]
Ah, I guess it's still possible to install Rack 2.0 with latest sinatra:

```ruby
# Gemfile
source 'https://rubygems.org'
gem 'sinatra'
gem 'rack', '2.0.0.alpha'
```

```ruby
# Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    json (1.8.3)
    rack (2.0.0.alpha)
      json
    sinatra (1.0)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  rack (= 2.0.0.alpha)
  sinatra

BUNDLED WITH
   1.11.2
```

I thought that `~> 1.5` meant it would only install `1.x` versions..

**Comment by zzak** [comment]
Whoops! Somehow, just doing `gem 'sinatra'` gave me version 1.0 which had `rack >= 1.0` as a dependency.. so it was fine. (Also weird that it just picked 1.0 instead of the latest version... hashtag bundler)

Here's what we get if you add the specific version to Gemfile:

```ruby
# Gemfile
source 'https://rubygems.org'
gem 'sinatra', '~> 1.4'
gem 'rack', '2.0.0.alpha'
```

```bash
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 2.0.0.alpha)

  In Gemfile:
    rack (= 2.0.0.alpha)

    sinatra (~> 1.4) was resolved to 1.4.0, which depends on
      rack (>= 1.5.2, ~> 1.5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by kgrz** [comment]
Oh! Will the sinatra 1.0 issue be a problem? Should we add a notice in README?

**Comment by lgustafson** [comment]
Tagging dependencies of a gem to specific versions is usually a mistake imo.  That should be up to the app developer.

**Comment by zzak** [comment]
@kgrz It was my mistake, because of rack constraint in the gemfile.. should be fine now though.

**Comment by zzak** [comment]
@lgustafson In our case, it does matter. Because we're actually extending another library (rack), and there will be API changes as we've already seen. So trying to support both and move the project forward are competing.

**Comment by lgustafson** [comment]
@zzak Actually it is a mistake in most cases because you're taking away the ability for an app developer to choose their own dependencies.  Problems should be discovered by writing tests in the application.  Between specifying soft dependencies in your documentation and your own version-controlled testing I don't think you're losing anything.

**Comment by zzak** [comment]
@lgustafson Just going to agree to disagree, so we can move on from this.

We won't be merging this patch and I suggest to wait until Sinatra 2.0 for Rack 2.0 support.

**Comment by jaredbeck** [comment]
Thanks everyone. My bad; I thought fixing #1055 was sufficient for rack 2 support.

> ..  I suggest to wait until Sinatra 2.0 for Rack 2.0 support.

Will do, thanks!

**Comment by zzak** [comment]
@jaredbeck No worries, thanks for your contribution!

**Pull request closed without merging**
