### PR TITLE
Add documentation for Multithreaded modes

### PR DESCRIPTION
**Pull request by kgrz**
Issue: https://github.com/sinatra/sinatra/issues/941
Discussion: https://github.com/sinatra/sinatra/issues/937

Although threading depends on the underlying Rack handler, the absence
of any mention of multi-threaded mode/concurrency seems to confuse users
and it was decided to add some pointers to clarify this.

### CODE REVIEW

**Comment by kgrz** [comment]
I probably should add a checklist for other languages. OR should I just use Google Translate?

**Comment by davydovanton** [comment]
@kgrz i can translate this to russian :smiley:

**Comment by kytrinyx** [comment]
Yeah, a checklist would be great. I can translate it to French.

**Comment by kgrz** [comment]
Done, added the checklist on the issue

**Comment by DyegoCosta** [comment]
@kgrz The Multi-threading section is missing a link on the Table of Content
And I'll translate it to pt-br

**Comment by kgrz** [comment]
@DyegoCosta Good catch! I've added the link under ToC.

Yes, the location under `Command Line` section was intentional since that was the part that talked about how to start the app. I can move it to a better place if you think there's one.

**Comment by DyegoCosta** [comment]
@kgrz I was just wondering. Since right now it is all about how to start the app I believe it's ok to be in the `Command Line` section. Apparently it won't get any bigger but if it does maybe it could have it own section :sweat_smile:

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
