### PR TITLE
add changes to transform_keys methods

### PR DESCRIPTION
**Pull request by aravindaakash**
This PR resolves issue number [1717](https://github.com/sinatra/sinatra/issues/1717)

### CODE REVIEW

**Comment by jkowens** [comment]
Thanks, can you check into the spec failures? I appreciate you working on this.

**Comment by jkowens** [comment]
Can you add a spec to cover this change?

**Comment by aravindaakash** [comment]
> Can you add a spec to cover this change?

Sure, I'll add the spec

**Comment by jkowens** [comment]
I'm really sorry @aravindaakash, I realized existing behavior is actually correct. It models the behavior of ActiveSupport::HashWithIndifferentAccess.

**Pull request closed without merging**
