### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
See #1072 

- [x] README.de.md 
- [x] README.es.md 
- [x] README.fr.md 
- [x] README.hu.md 
- [x] README.ja.md 
  - [x] fix japanese wiki link
- [x] README.ko.md	 
- [x] README.pt-br.md	 
- [x] README.pt-pt.md	 
- [x] README.ru.md	 
  - [x] fix russian wiki link
- [x] README.zh.md

### CODE REVIEW

**Comment by jkowens** [comment]
In `README.zh.md` and `README.pt-pt.md` the broken url:
http://haml.info/docs/yardoc/file.HAML_REFERENCE.html#options can be replaced with:
http://haml.info/docs/yardoc/file.REFERENCE.html#options

Although it seems like that section must have been removed in other languages.

**Comment by ReadmeCritic** [comment]
@jkowens updated

**Comment by jkowens** [comment]
:+1:

**Comment by kgrz** [comment]
This is wonderful! Thank you @jkowens and @ReadmeCritic!

**Comment by ReadmeCritic** [comment]
:smile:

**Pull request merged**
