### PR TITLE
Fix warnings `Use assert_nil if expecting nil from ...`

### PR DESCRIPTION
**Pull request by iguchi1124**
This will fail in MT6

### CODE REVIEW

**Comment by burningTyger** [comment]
:) a couple of hours ago I had the exact same idea in #1221 Obviously I missed two cases.

**Comment by iguchi1124** [comment]
@burningTyger oh, I'm sorry missing your pull request :bow: 
I close this PR soon.

**Comment by burningTyger** [comment]
No, open it again. Yours is more complete and can be merged as well.

**Comment by zzak** [comment]
@iguchi1124 @burningTyger Thank you both!! :bowing_man:

**Pull request merged**
