### PR TITLE
Update Rubies to the latest version for Travis CI.

### PR DESCRIPTION
**Pull request by junaruga**
Let's update Travis CI.

### CODE REVIEW

**Comment by namusyaka** [comment]
Related to #1450

**Comment by olleolleolle** [comment]
These are the versions we're looking for - exact and updated. 👍

**Comment by junaruga** [comment]
I prefer #1450 way personally to update the each Ruby version automatically.

**Comment by junaruga** [comment]
Which PR do we merge? This PR or #1450?

**Pull request closed without merging**
