### PR TITLE
Update changelog since last release

### PR DESCRIPTION
**Pull request by epergo**
:wave: Hello there! I was having a look att what has been merged since the last release since it's been a while (September 2020) and decided to update the CHANGELOG.

WDYT? Did I miss anything?

---

It's true that we didn't merge anything super important that should be released asap but I think we already have quite some things, maybe is time to cut a release?

### CODE REVIEW

**Comment by jkowens** [comment]
We 2.2 release so bad...and then a 3.0 release from the unstable branch.  @zzak @namusyaka is there anything that can be done to get a release cut? We still have a few people interested in helping on this project, but the lack of releases is thoroughly discouraging.

**Comment by dentarg** [comment]
> It's true that we didn't merge anything super important that should be released asap

Well, actually... 

* 2.1.0 had some (unintentional) breaking changes, that have been fixed: 
  * https://github.com/sinatra/sinatra/pull/1649
  * https://github.com/sinatra/sinatra/pull/1662
* And in terms Ruby 3 compatibility these fixes not yet released
  * https://github.com/sinatra/sinatra/pull/1684
  * https://github.com/sinatra/sinatra/pull/1701
 
(These included in the changelog update here, so thanks!)

**Comment by EduardoSimon** [comment]
Hi, is a 2.2.0 release planned then? We need to update our codebase to ruby 3.0 and pointing to master is not an option TBH.

**Comment by Kjarrigan** [comment]
A big :+1: for a release from me as well. Using master is no option for me either otherwise I would need to switch to something like grape which I really would like to avoid.

**Pull request merged**
